<?php


namespace App\Command;


use App\Services\Generator\WriteToExcel;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CreateExcelBackupCommand extends Command
{
    protected static $defaultName = 'app:create:excel';
    private WriteToExcel $writeToExcel;

    public function __construct(
        WriteToExcel $writeToExcel,
        string $name = null)
    {
        $this->writeToExcel = $writeToExcel;
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('Create excel backup')
            ->setHelp('This command allows you to create excel backup data');

        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $this->writeToExcel->writeToExcel();

        $output->writeln([
            "Excel file saved",
            "================="
        ]);

        return Command::SUCCESS;
    }


}