<?php


namespace App\Form\Type;


use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('name', TextType::class)
            ->add('slug', TextType::class)
            ->add('task', TextType::class)
            ->add('dueDate', DateType::class)
            ->add('save', SubmitType::class, ['label' => 'Create Task'])
            ;
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefault([
            'data_class' => Task::class,
        ]);
    }
}